enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
exclusive-patches = true
included-patches = "'Hide ads' 'Disable signature check'"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
exclusive-patches = true
included-patches = "'GmsCore support' 'Spoof features' 'Change package name'"
arch = "arm64-v8a"
